### PR TITLE
feat: useSkoy() hook

### PR DESCRIPTION
**Pull request by santhitak**

### CODE REVIEW

**Review by narze — CHANGES_REQUESTED** [review]
image

**Comment by narze** [comment]
Maybe install with `npm install --save-dev skoy`

**Comment by santhitak** [comment]
> Maybe install with `npm install --save-dev skoy`

all done kub!

**Review by leomotors — APPROVED** [review]
กร๊บครั๊ผ ภิ๊อ๊ร์คุ๊ลภ๊ภม่กๆคร่๊

**Review by narze — APPROVED** [review]

**Pull request merged**
