### PR TITLE
feat: add useHijack

### LINKED ISSUE #118: A hook that make React unusable, make other hooks dead, etc.
i.e. A hook to rule them all

### PR DESCRIPTION
**Pull request by wiennat**
Add useHijack. It hijacks React to breaks the page. Navigation does not work after it is hijacked.
It is one hook to rule them all. Close #118 when merged.

### CODE REVIEW

**Review by leomotors — APPROVED** [review]
F

**Review by tinarskii — APPROVED** [review]
Lmao this is so cute and funny😭😭😭😭😭

**Comment by leomotors** [comment]
@tinarskii

**Review by ronnapatp — APPROVED** [review]
:armWeed:

**Pull request merged**
