### PR TITLE
[Feat] Improve Docs

### PR DESCRIPTION
**Pull request by runyasak**
# Overview

I create docs for react-useless project with mobile responsive.

# Scope of work
* Convert to docs website with route
* Implement UI with Tailwindcss & Daisyui
* I have converted some hooks to docs. For the rest, I put them to `AllHooksPage`

# Screenshots
image

image

### CODE REVIEW

**Comment by narze** [comment]
Nice work!
By the way I doubt that contributors will create a separate page & component though...

**Comment by narze** [comment]
Maybe update the readme to instruct on adding docs?

**Comment by runyasak** [comment]
> Maybe update the readme to instruct on adding docs?

Good idea.
We should make the contribution guide for separate pages.
We can discuss more in Discord. 😁

**Comment by narze** [comment]
[diff.patch.txt](https://github.com/narze/react-useless/files/9691922/diff.patch.txt)

```diff
diff --git a/src/hooks-usage/_TEMPLATE.tsx b/src/hooks-usage/_TEMPLATE.tsx
index 782de4c..063d7a4 100644
--- a/src/hooks-usage/_TEMPLATE.tsx
+++ b/src/hooks-usage/_TEMPLATE.tsx
@@ -2,7 +2,7 @@
 
 import Card from "../components/Card"
 
-import { useLess } from "../hooks/useLess"
+import { useLess } from "../hooks/useLess/useLess"
 import { useSalim } from "../hooks/useSalim"
 
 // Default export a functional component which includes hook's usage
diff --git a/src/hooks-usage/useLess.tsx b/src/hooks-usage/useLess.tsx
index 7d613bc..4297378 100644
--- a/src/hooks-usage/useLess.tsx
+++ b/src/hooks-usage/useLess.tsx
@@ -1,5 +1,5 @@
 import Card from "../components/Card"
-import { useLess } from "../hooks/useLess"
+import { useLess } from "../hooks/useLess/useLess"
 
 export default function () {
   const cardProps = {
diff --git a/src/hooks/useLess/useLess.ts b/src/hooks/useLess/useLess.ts
index 18ac1d9..44ab28c 100644
--- a/src/hooks/useLess/useLess.ts
+++ b/src/hooks/useLess/useLess.ts
@@ -1,5 +1,5 @@
 import { useState } from "react"
-import { DefinitelyNotAny } from "./types"
+import { DefinitelyNotAny } from "../types"
 
 export function useLess(initialValue: DefinitelyNotAny) {
   const [value, _setValue] = useState(initialValue)
diff --git a/src/hooks/useVoid/useVoid.ts b/src/hooks/useVoid/useVoid.ts
index ee5f394..be62b6a 100644
--- a/src/hooks/useVoid/useVoid.ts
+++ b/src/hooks/useVoid/useVoid.ts
@@ -1,5 +1,5 @@
 import { useLayoutEffect } from "react"
-import { DefinitelyNotAny } from "./types"
+import { DefinitelyNotAny } from "../types"
 
 export function useVoid(...args: DefinitelyNotAny[]) {
   useLayoutEffect(() => {
```

**Review by narze — APPROVED** [review]
let's goooo

**Pull request merged**
